/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/**/*.{html,js}", "./static/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary": "#003915",
              "surface": "#0c160d",
              "on-primary-fixed-variant": "#005322",
              "charcoal-grey": "#1A1A1C",
              "inverse-surface": "#dbe6d7",
              "surface-dim": "#0c160d",
              "glass-fill": "rgba(10, 10, 11, 0.7)",
              "background": "#0c160d",
              "primary-container": "#32ff7e",
              "surface-container-highest": "#2d372d",
              "primary": "#f3fff0",
              "on-tertiary": "#3e2e00",
              "secondary-fixed": "#e5e2e3",
              "cyber-lime": "#32FF7E",
              "secondary": "#c8c6c7",
              "surface-container-lowest": "#071008",
              "tertiary-fixed-dim": "#e5c36f",
              "inverse-primary": "#006d2f",
              "surface-container-low": "#141e15",
              "surface-container": "#182219",
              "on-surface-variant": "#bacbb8",
              "inverse-on-surface": "#293329",
              "on-secondary-fixed": "#1c1b1c",
              "on-primary-fixed": "#00210a",
              "surface-variant": "#2d372d",
              "on-tertiary-container": "#795f14",
              "secondary-container": "#4a494a",
              "secondary-fixed-dim": "#c8c6c7",
              "warning-amber": "#FF9F1A",
              "tertiary-fixed": "#ffdf95",
              "surface-tint": "#00e46b",
              "surface-container-high": "#232c23",
              "primary-fixed": "#66ff8f",
              "on-error-container": "#ffdad6",
              "outline": "#849583",
              "glass-stroke": "rgba(255, 255, 255, 0.12)",
              "tertiary-container": "#ffdb85",
              "on-primary-container": "#007232",
              "tertiary": "#fffbf9",
              "on-secondary-container": "#bab8b9",
              "error-container": "#93000a",
              "error": "#ffb4ab",
              "neon-crimson": "#FF3F34",
              "on-background": "#dbe6d7",
              "on-secondary": "#313031",
              "on-tertiary-fixed": "#251a00",
              "outline-variant": "#3b4b3c",
              "on-secondary-fixed-variant": "#474647",
              "on-tertiary-fixed-variant": "#594400",
              "on-error": "#690005",
              "on-surface": "#dbe6d7",
              "surface-bright": "#323c32",
              "primary-fixed-dim": "#00e46b"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "component-gap": "12px",
              "gutter": "16px",
              "container-margin": "24px",
              "base": "8px"
      },
      "fontFamily": {
              "body-md": [ "Inter" ],
              "headline-lg": [ "Inter" ],
              "data-display": [ "JetBrains Mono" ],
              "label-caps": [ "Inter" ],
              "headline-md": [ "Inter" ],
              "code-sm": [ "JetBrains Mono" ]
      },
      "fontSize": {
              "body-md": [ "16px", { "lineHeight": "1.6", "fontWeight": "400" } ],
              "headline-lg": [ "32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" } ],
              "data-display": [ "14px", { "lineHeight": "1.4", "fontWeight": "500" } ],
              "label-caps": [ "11px", { "lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "700" } ],
              "headline-md": [ "24px", { "lineHeight": "1.3", "fontWeight": "600" } ],
              "code-sm": [ "12px", { "lineHeight": "1.5", "fontWeight": "400" } ]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
